### ISSUE TITLE
Revamp reallocations to use Budget Events and Budget Line Items tables for better tracking instead of a text field.

### ISSUE THREAD

**Issue by kcbimonte** [WPI-SGA-Financials/Financial-Database-SQL#6]
- [ ] Change Reallocations table structure to reallocation -> legacy and current
- [ ] Current should have the following fields (R_ID, From_BLI, To_Existing?, Existing_BLI, New Descript, Transfer_Amount, Notes, Timestamp)
- [ ] Migrate Legacy to the new structure if possible
